### ISSUE TITLE
please implement imgur 

### ISSUE THREAD

**Issue by ghost** [lilydjwg/HTTPSEverywhereUserRules#2]
I add it by gui tools. But you can write a rule to force imgur to use https://

**Comment by lilydjwg** [comment]
What is the url? I tried several and they all redirect to the HTTPS version because HTTPEverywhere already has a rule for them.

**Comment by rtlanceroad** [comment]
Sorry, you are right. I somewhat had it disabled before even I dont know.... I just search rules, I have 2 rules about it with different names... one is open, the other is closed.... My fault. Sorry for bothering.
